### ISSUE TITLE
SSB calculation with external wtatage

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-stock-synthesis/stock-synthesis#103]
Figure out mismatch in SSB calculations for model shared by Iago Mosqueira in [this VLab forums post](https://vlab.ncep.noaa.gov/web/stock-synthesis/public-forums/-/message_boards/message/12091248?_com_liferay_message_boards_web_portlet_MBPortlet_orderByCol=modified-date&_com_liferay_message_boards_web_portlet_MBPortlet_scStart=0&_com_liferay_message_boards_web_portlet_MBPortlet_delta=50&_com_liferay_message_boards_web_portlet_MBPortlet_orderByType=desc&_com_liferay_message_boards_web_portlet_MBPortlet_index=0&_com_liferay_message_boards_web_portlet_MBPortlet_scEnd=50&_com_liferay_message_boards_web_portlet_MBPortlet_showBreadcrumb=false&_com_liferay_message_boards_web_portlet_MBPortlet_resetCur=false&_com_liferay_message_boards_web_portlet_MBPortlet_categoryId=971356&_com_liferay_message_boards_web_portlet_MBPortlet_cur1=1).

**Comment by Rick-Methot-NOAA** [comment]
We should test this after fixing wt-at-age updating per #138

**Comment by iantaylor-NOAA** [comment]
Thanks for the reminder to revisit this, @Rick-Methot-NOAA.

I just confirmed the same small mismatch using 3.30.18.
SSB_2019 reported in Report.sso is 8128
That same value calculated as the product of the beginning-of-year numbers at age from Report.sso and fecundity at age from wtatage.sso is 8216. Difference is only 1% but seems too large for rounding error. Difference is not present in hake model.

I'm re-assigning to you and will email you the associated files.

**Comment by Rick-Methot-NOAA** [comment]
This mismatch occurs because the external calculation erroneously uses the age 0 fish.
In this vendance example, the age 0 fish have tiny, but non-zero fecundity.
In the internal calc of SSB at beginning of the year, the age 0 fish do not yet exist, so are not included in the SSB.
In this annual model configuration, recruitment of age 0 fish then occurs immediately after the SSB is calculated.
These age 0 fish are in the N-at-age table output for the beginning of the year.
So, the external calculation is different and incorrect  due to inclusion of the age 0 fish in the SSB.
