### ISSUE TITLE
dirichlet multinomial parameters must be labeled consecutively

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#152]
It looks like Dirichlet multinomial parameters must be labeled consecutively from 1 to the last parameter in defining them in the data file in order for SS to read them correctly. For example, say a user has a model with DM parameters labelled 1 to 4 in the data file. If a user decides to drop a fleet, say, the one associated with DM parameter 1, then there will only be DM parameters for 2 to 4 (3 total parameters). SS will stil expect to read 4 parameter lines in the control file, though, and will exit on error when it cannot figure out which fleet parameter 1 (which is not longer being used)  belongs with. 

I think it would be helpful to either 1) exit on error and provide an informative msg when users have not used consecutive parameter numbers for DM in the data file or 2) revise the DM parameter option so that users do not need consecutive parameter numbers. The first is the simpler of the options, but I could see 2) being more useful.

**Comment by Rick-Methot-NOAA** [comment]
I will take a look at this.  Please send me an example setup in which I can invoke the problem.

**Comment by k-doering-NOAA** [comment]
Thanks, just forwarded you an email with an example.

**Comment by Rick-Methot-NOAA** [comment]
The numbering of the requested D-M parameters must be consecutive and cannot exceed Nfleet.
I created a fatal warning if user tries to assign a D-M index > Nfleet.
I have not created an algorithm to figure out if any number gets skipped in the sequence.

So, this is legit and will take 6 parameters:
#_mintailcomp	addtocomp	combine_M_F	CompressBins	CompError	ParmSelect	minsamplesize
-0.001	1e-07	0	10	1	 1	0.01	#_f2_volpal  
-0.001	1e-07	0	10	1	 2	0.01	#_f3_trawlers
-0.001	1e-07	0	10	1	 3	0.01	#_f4_art     
-0.001	1e-07	0	10	1	 4	0.01	#_f5_cdtrw   
-0.001	1e-07	0	10	1	 4	0.01	#_SpSurv     
-0.001	1e-07	0	10	1	 5	0.01	#_CdSurv     
-0.001	1e-07	0	10	1	 5	0.01	#_PtSurv     
-0.001	1e-07	0	10	1	 5	0.01	#_SpCPUE     
-0.001	1e-07	0	10	1	6	0.01	#_PtCPUE     

but this is not legit because one number is skipped #_mintailcomp	addtocomp	combine_M_F	CompressBins	CompError	ParmSelect	minsamplesize
-0.001	1e-07	0	10	1	 1	0.01	#_f2_volpal  
-0.001	1e-07	0	10	1	 2	0.01	#_f3_trawlers
-0.001	1e-07	0	10	1	 4	0.01	#_f4_art     
-0.001	1e-07	0	10	1	 4	0.01	#_f5_cdtrw   
-0.001	1e-07	0	10	1	 4	0.01	#_SpSurv     
-0.001	1e-07	0	10	1	 5	0.01	#_CdSurv     
-0.001	1e-07	0	10	1	 5	0.01	#_PtSurv     
-0.001	1e-07	0	10	1	 5	0.01	#_SpCPUE     
-0.001	1e-07	0	10	1	6	0.01	#_PtCPUE

**Comment by k-doering-NOAA** [comment]
Ok, thanks for confirming @Rick-Methot-NOAA .

I added [a warning in the r4ss fxn to read datafiles](https://github.com/r4ss/r4ss/commit/472463b5d4e0396070fb239936d65bbc131e6c3e) that does check that there aren't any skipped values. But I could see how this algorithm to do the check would be more lines of code (and hence more time to create) in c++ code...

Perhaps the one other mitigation (besides adding the warning in SS) that could be done would be to add to the user manual?

**Comment by Rick-Methot-NOAA** [comment]
Yes!  Please do add to the user manual.

**Comment by k-doering-NOAA** [comment]
Great, I added a sentence to the manual clarifying that  parameter numbers cannot be skipped. I think this can be closed if there won't be any more changes to the ss source code. Thanks @Rick-Methot-NOAA !

**Comment by chantelwetzel-noaa** [comment]
I think the trap created to check for sequential numbering has led to the issue reported by @skylersagarese-NOAA.  The DM parameter number can and often does exceed the fleet number is length and age data are both in the model.  It looks like the model stops if this issue is identified 

https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/56036dde7cafc96ac83dc066d3bd4fdb8d73733a/SS_readdata_330.tpl#L1751

this could be a high priority fix if my interpretation is correct.

**Comment by k-doering-NOAA** [comment]
Thanks @chantelwetzel-noaa , you were spot on! Now fixed in #184 .
