### ISSUE TITLE
add option to include summary biomass time series in DERIVED_QUANTITIES

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-stock-synthesis/stock-synthesis#168]
As noted in https://github.com/r4ss/r4ss/issues/524, summary biomass is a useful metric for many models as an approximation for available biomass and a common framework to compare models that have different maturity or fecundity relationships (as is sometimes then case when comparing new vs old assessments of the same stock).

@IJStewart pointed out that such comparisons would be even more useful if the uncertainty in summary biomass were available.

I'm guessing that the hardest part of this request would be figuring out the best input format for the switch.
It could utilize `More_Std_Input(13)` (currently reserved for future use within the Dynamic B0 setup #75 as shown at
https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/main/SS_readcontrol_330.tpl#L4189.
Alternatively a new `Do_More_Std == 3` option could be added which would extend the inputs beyond the 13 values currently associated with `Do_More_Std == 2`.

**Comment by Rick-Methot-NOAA** [comment]
Thanks Ian for queueing this up neatly.
Since there probably are very few users who are using  Do_More_Std==2, I support inplementing this as a modification of that option that will now require input for   Do_SmryBio_se=More_Std_Input(13) immediately after the current input for Bzero.  After that, the code for implementing this will largely be the same as what was done for Bzero.

**Comment by iantaylor-NOAA** [comment]
I realized that unlike other time series quantities that are included in DERIVED_QUANTITIES, Summary Biomass is calculated in each season for a multi-season model. I'm guessing that it would be just fine to provide those values only from Season 1.

**Comment by Rick-Methot-NOAA** [comment]
I have completed this augmentation.
A question - location in the output.
Option A (implemented):  
remove the old SmryBio output that was located in the Biology section at end of ss_summary
insert new SmryBio section, with se, right after the ln(SSB) output and before the other extra_std quantities.  This was easy because all are components of the extra_std vector.  Note that the change in order will cause a Jenkins fail and may need r4ss update.

Option B (a lot more work, but possible):  keep smrybio output in same place but now let it have se.
This is more work because of the order in which labels are created for the std quantities.

Let me know if you really, really want option B.

**Comment by Rick-Methot-NOAA** [comment]
While working on this, I noted that the values of SmryBio and TotBio in forecast years kept increasing.  Turns out that the accumulator code in SS_benchfore was not working properly.  
Fixed this and ran a compare of these quantities as reported in ss_summary.sso, to the independently calculated quantities in TimeSeries of report.sso.  They match.  Case closed.

**Comment by Rick-Methot-NOAA** [comment]
control.ss_new now looks like:
2 # (0/1/2) read specs for more stddev reporting: 0 = skip, 1 = read specs for reporting stdev for selectivity, size, and numbers, 2 = add options for M and Dyn Bzero
 1 1 -1 5 # Selectivity: (1) 0 to skip or fleet, (2) 1=len/2=age/3=combined, (3) year, (4) N selex bins; NOTE: combined reports in age bins
 1 5 # Growth: (1) 0 to skip or growth pattern, (2) growth ages; NOTE: does each sex
 1 -1 5 # Numbers-at-age: (1) 0 or area(-1 for all), (2) year, (3) N ages;  NOTE: sums across morphs
 0 0 # Mortality: (1) 0 to skip or growth pattern, (2) N ages for mortality; NOTE: does each sex
2 # Dyn Bzero: 0 to skip, 1 to include, or 2 to add recr
1 # SmryBio: 0 to skip, 1 to include

**Comment by iantaylor-NOAA** [comment]
The way you've implemented it seems just fine to me.
Is the only change in Report.sso is the addition of the SmryBio rows after ln(SSB) in DERIVED_QUANTITES?

I would change the first line in control.ss_new from
`2 = add options for M and Dyn Bzero`
to
`2 = add options for M, Dyn Bzero, and SmryBio`.

Here are a few more things to do before closing this issue (if there are no other concerns about how it's implemented):
- [ ] change SS tests to adapt to difference in ss_summary.sso (and maybe modify one of the test models to use this new option)
- [ ] change r4ss as needed
- [ ] add documentation of the new SmryBio option to the User Manual
- [ ] document Dyn Bzero option 2 (@Rick-Methot-NOAA, can you explain what the "2 to add recr" does?)

**Comment by Rick-Methot-NOAA** [comment]
The option 2 to add Dyn Recr simply appends the time series of Recruitment
after the time series of SSB in the dynamic Bzero section.

**Comment by k-doering-NOAA** [comment]
This creates a breaking change for anyone who was using option 2 just for natural mortality inputs in previous versions of SS. We may want to note this in the change log and perhaps a warning in r4ss.

**Comment by Rick-Methot-NOAA** [comment]
I don't understand how this interacts with natural mortality.  Does this
seem fixable easily?

**Comment by k-doering-NOAA** [comment]
I think in 3.30.16 (and 15?), option 2 inputs looked like:
```r
2 # (0/1/2) read specs for more stddev reporting: 0 = skip, 1 = read specs for reporting stdev for selectivity, size, and numbers, 2 = add options for M 
1 1 -1 5 # Selectivity: (1) 0 to skip or fleet, (2) 1=len/2=age/3=combined, (3) year, (4) N selex bins; NOTE: combined reports in age bins
1 5 # Growth: (1) 0 to skip or growth pattern, (2) growth ages; NOTE: does each sex
1 -1 5 # Numbers-at-age: (1) 0 or area(-1 for all), (2) year, (3) N ages; NOTE: sums across morphs
0 0 # Mortality: (1) 0 to skip or growth pattern, (2) N ages for mortality; NOTE: does each sex
```

In 3.30.17 with the new dynamic b0 and smry biomass options, more inputs are needed (2 extra values at the bottom)
```r
2 # (0/1/2) read specs for more stddev reporting: 0 = skip, 1 = read specs for reporting stdev for selectivity, size, and numbers, 2 = add options for M and Dyn Bzero
1 1 -1 5 # Selectivity: (1) 0 to skip or fleet, (2) 1=len/2=age/3=combined, (3) year, (4) N selex bins; NOTE: combined reports in age bins
1 5 # Growth: (1) 0 to skip or growth pattern, (2) growth ages; NOTE: does each sex
1 -1 5 # Numbers-at-age: (1) 0 or area(-1 for all), (2) year, (3) N ages; NOTE: sums across morphs
0 0 # Mortality: (1) 0 to skip or growth pattern, (2) N ages for mortality; NOTE: does each sex
2 # Dyn Bzero: 0 to skip, 1 to include, or 2 to add recr
1 # SmryBio: 0 to skip, 1 to include
```

I think this means that 3.30.16 models that used variance of M options previously would no longer work with 3.30.17, because they are missing 2 values.

I suspect there are not too many models like this, so maybe it is ok to make a breaking input change? An alternative s to add an option 3 for read specs for more stddev reporting.

**Comment by Rick-Methot-NOAA** [comment]
The M options are still there in 3.30.17, but now they are followed by the
Dyn Bzero options

**Comment by k-doering-NOAA** [comment]
Yes, but that means an older model that has used the M options won't have the Dyn Bzero/ Summary biomass options inputs (because they weren't expected inputs at the time) and won't be parsed correctly when reading into SS (I assume this model would error with 3.30.17).

There's nothing internally wrong with the implementation in SS, but we just need to decide if we are OK with this being  a breaking input change for previous users of option 2 and make sure this is communicated.

**Comment by k-doering-NOAA** [comment]
sounds good, Rick. I am making a note in the documentation now.
