### ISSUE TITLE
Numbering of D-M parameters when both length and age composition input (exceeds Nfleet)

### ISSUE THREAD

**Issue by skylersagarese-NOAA** [nmfs-stock-synthesis/stock-synthesis#183]
Issue #152 implemented an error if the number of D-M exceeds the number of fleets, but if both length and age composition are included for fleets, the number of D-M can exceed Nfleet according to Page 56 in the manual:

![image](https://user-images.githubusercontent.com/65174446/121906524-30a56200-ccf9-11eb-920b-65b96ca66c1d.png)

For our Gulf models (scamp grouper example below), which often incorporate both length and age compositions for fishing fleets, we get the following error because Nfleet = 6 but additional D-Ms are needed for the age data. 

Control file:
...
#_mintailcomp addtocomp combM+F CompressBins CompError ParmSelect minsamplesize
-1 1e-003 0 0 1 1 1 #_fleet:1_ComVL
-1 1e-003 0 0 1 2 1 #_fleet:2_ComLL
-1 1e-003 0 0 1 3 1 #_fleet:3_Charter_Private
-1 1e-003 0 0 1 4 1 #_fleet:4_Headboat
-1 1e-003 0 0 1 5 1 #_fleet:5_Combined_Video
-1 1e-003 0 0 1 6 1 #_fleet:6_RFOP_Index
...
#_mintailcomp addtocomp combM+F CompressBins CompError ParmSelect minsamplesize
-1 1e-003 0 0 1 7 0.001 #_fleet:1_ComVL

Warning file:
1; Age D-M index for fleet: 1 is: 7 but must be an integer <=Nfleet 

Please let us know if you require additional information. Thanks!

**Comment by Rick-Methot-NOAA** [comment]
This will take a careful investigation.  Looks like the indexing of D-M parameters is being too closely linked to Nfleets.

**Comment by Rick-Methot-NOAA** [comment]
Working now for hake and scampi
Also changed the parameter label to a more informative:  ln(DM_theta)_Age_P7(2)

code now detects and exits if a parameter number is skipped

**Comment by Rick-Methot-NOAA** [comment]
@k-doering-NOAA  can you check to see if the revised parameter labels work OK with r4ss.  Note that I put the fleet at the end of the label in ().  This is same as for selectivity parameters.  If that is OK, then I think we can pull this into main.  Note that I updated version to 3.30.17.01.
Overall, I think the logic for this indexing and labeling approach is now much stronger

Rick

**Comment by k-doering-NOAA** [comment]
Rick, I will check on the param labels shortly.

@skylersagarese-NOAA, would you mind [testing this version of SS](https://github.com/nmfs-stock-synthesis/stock-synthesis/suites/2993776607/artifacts/67640084) with your model?

**Comment by skylersagarese-NOAA** [comment]
Worked perfectly! Thank you!

Sky

**Comment by k-doering-NOAA** [comment]
thanks @skylersagarese-NOAA !

@Rick-Methot-NOAA , about the labels, I think they shouldn't have a fleet specific label since the parameters can be shared amongst multiple fleets - when I ran a model with a shared parameter, it just showed the first fleet value, which may be confusing.

A side note,I think using the "_" or "-" separator rather than "(" is better with R because "(" is often used in regular expressions and is not a standard component of R names (although there are workarounds, so it isn't the end of the world). Just an FYI, for SSMSE, we do have to pull out parameter values using their names as in SS, and will need to modify the code as SS labels change; So not changing the labels unless there is a good reason (making labels more clear does seem a good reason!) to do so would be helpful for us, and possibly for other folks using SS with custom tools.

I tested the SS_tune_comps, SS_output, SS_plots, and SS_read/write_ctl/dat functions with the new parameter labels and  there were no issues.

**Comment by iantaylor-NOAA** [comment]
When looking at the Pull Request (https://github.com/nmfs-stock-synthesis/stock-synthesis/pull/184#pullrequestreview-683231210), I didn't think about the problem @k-doering-NOAA noted of fleet numbers in the labels when parameters are shared among fleets case.
Maybe a better solution is to add the design matrix of D-M parameter assignments to fleets as a new table in Report.sso, but perhaps that should wait for the next version of SS.

**Comment by Rick-Methot-NOAA** [comment]
I am totally agnostic about implementation of the parameter labels; just
want them to be informative.

I will use a "_" for fleet in the D-M parameters.  QUESTION:  I can easily
change the selectivity parameters to be the same, but await advice from R
gurus.

Ian - good suggestion regarding the table and I was worried about that
issue also.   Such a design matrix does appear in echoinput, but hardly
adequate for what users need.  I think adding it to report.sso is fine
idea.  But let's do that after this fix is over.

Rick

**Comment by kellijohnson-NOAA** [comment]
Couldn't you use a delimiter and just paste the fleets together if there are multiple? e.g., ln(DM_theta)_Age_P7(2-3-4)
For what it is worth, I like the correct mathematical notation of ln(DM_theta) because it helps the visually impaired when a screen reader is reading the output. I think there are ways in tidyverse to accommodate the parenthesis, at least you can with backticks but I think there are other ways as well.

**Comment by kellijohnson-NOAA** [comment]
Sorry, I should have put e.g., e.g., ln(DM_theta)_Age_P7_2-3-4

**Comment by Rick-Methot-NOAA** [comment]
ln(DM_theta)_Age_P7_2-3-4 is possible, but a good bit of additional code to
save info on more than just the first referenced fleet

**Comment by iantaylor-NOAA** [comment]
I like @kellijohnson-NOAA's proposed labels, but given the extra coding required, that changes seems to go beyond the immediate need for a 3.30.17.01 bug fix, so how about just leaving off the fleet number from the parameter labels and reported issue and then circling back to refine the labels and/or report the parameter design matrix at a later time.

**Comment by Rick-Methot-NOAA** [comment]
concur with Ian's suggestion.  Will implement accordingly and pull into
main.

**Comment by k-doering-NOAA** [comment]
Sounds good, I like the suggestion to consider this at a different time.

@Rick-Methot-NOAA I suggest not changing the selectivity; like Kelli said, there are ways to deal with it, and status quo is fine.

**Comment by k-doering-NOAA** [comment]
@Rick-Methot-NOAA , should this be released as a fix? I can tag the repo (making sure it is labeled 3.30.17.01), and then upload all the executables to vlab if so.

**Comment by Rick-Methot-NOAA** [comment]
Yes.  Please do post as a fix.

**Comment by k-doering-NOAA** [comment]
The [3.30.17.01 exes](https://vlab.noaa.gov/web/stock-synthesis/document-library/-/document_library/0LmuycloZeIt/view/6427430) are now available, so closing this issue.
