### ISSUE TITLE
Issue matching 3.24 and 3.30 models: expected index different 

### ISSUE THREAD

**Issue by Cole-Monnahan-NOAA** [nmfs-stock-synthesis/stock-synthesis#190]
I am converting an old 3.24U model to 3.30.17. I was unable to use sstrans so doing things manually.

At this point I have the dynamics matching exactly given the same input parameters. So numbers at age, total biomass, SSB, all these are very close, which tells me that the dynamics are equivalent.  

However, when I compare the expected index (Vuln_bio in r4ss) I see substantial differences. 

````
'data.frame':	15 obs. of  4 variables:
 $ Bio_all_old : int  198302 217842 221928 219026 218623 216667 216581 220192 223327 227581 ...
 $ Bio_all_new : int  198306 217846 221933 219031 218628 216670 216586 220197 223332 227586 ...
 $ Vuln_bio_old: int  194111 212047 217585 211659 210349 213239 209268 210248 216855 218486 ...
 $ Vuln_bio_new: int  175117 191537 195890 189860 188555 192251 188153 188757 194682 195876 ...
````

The old Vuln_bio makes sense since selex is high for almost all ages. I verified that the two models match for Q (=1), selectivity at age and length (estimated as type 20 age selex) and minimum age for summary calcs (0).

I'm at a bit of a loss on where this difference could come from other than some sort of seasonal timing. But then again if the seasonality were off, the dynamics would be off as well. And the difference in expected index seems too large to be caused by a within-year difference. So it's got to be just something in the calculation of dynamics to expected index, right?

@kellijohnson-NOAA suggested posting here as this might be related to a bug fix or something similar. 

Any pointers at places to look? I can share files privately if that helps.

**Comment by Rick-Methot-NOAA** [comment]
Hi Cole,
There is no obvious change that would account for this, especially given the very large number of assessments that have been successfully converted.  Send me the whole set of 3.24 files and I'll get them converted, then post here the steps I go through in that process.
Rick

**Comment by iantaylor-NOAA** [comment]
3.24 had index observations associated with a particular season, whereas in 3.30, they are associated with a month. An input of month = 7 should cause the new and old values to match, but if your 3.30 model has month = 1 (not converted from season = 1), then maybe either the beginning of year weight-at-age would have been used or a half-year of natural mortality would not yet have been applied creating an offset. 

If you're comparing models with the same fixed input parameters, then I don't think that a shift in estimated vulnerable biomass would impact the dynamics (and it would mostly come out in the wash if you estimate the parameters due to confounding with Q).

Sending files to Rick is the more reliable solution, regardless.

**Comment by Cole-Monnahan-NOAA** [comment]
@iantaylor-NOAA I tried both of those and they change the expected index but not by much, much too small to make the difference. I'm pretty confused about how subseasons and timing work even after reading the manual, so there could be something else similar I did wrong there.

**Comment by Rick-Methot-NOAA** [comment]
Cole,
please replicate my steps below.  I was able to get all the ss_new files created using the ss_trans distributed with 3.30.17.
Note that you should turn off reading of ss.par.

RUN 1:    I tried ss_trans with -nohess and -maxL 0.  
SS reads all files and executes one iteration.  
Then dies with:
1 2 -log(L): 6553.69  Spbio: 18424.3 8982.37
In final section
Finish time: Thu Jul 08 14:29:14 2021
Elapsed time: 0 hours, 0 minutes, 0 seconds.
 Iterations: 2 -log(L): 6553.69
Final gradient: 3.13908e-14

 got Fspr 0.171756 0.4
 got_Btgt 0.20657 0.35
 got Fmsy 0.619469 4606.64
 finished benchmark
 finished forecast
array bound exceeded -- index too low in prevariable::operator().

RUN 2:  Then I ran again with -maxI -1 which skips all calculations and goes straight to write
 reading forecast file
 reading from control  file
If you see 999, we got to the end of the control file successfully! 999
 end of parameter section
 ready to evaluate once in prelim
 Requested exit after read when turn_off_phase < 0
 finished nudata report
 Write new starter file
 Write new forecast file
 Write new control file
 finished nucontrol report

**Comment by Rick-Methot-NOAA** [comment]
got the ss_trans problem.
3.24 data file had:
 -1 0 #_surveytiming_in_season #revisit - I think it's 1 in Buck's model (after all of the mortality)
The "0" value made ss_trans think this survey occurs on Jan 1, so created month=1 in data.ss_new for both the index and the comp data.
But the "0" itself got converted to a "nan" in that fleet definition section of data.ss_new, so 3.30 failed when it tried to read the converted data file.

change to:
 -1 .5 #_surveytiming_in_season #revisit - I think it's 1 in Buck's model (after all of the mortality)
in the original data file and ss_trans should work file.

**Comment by Rick-Methot-NOAA** [comment]
I ran 3.24 to completion and got:
 76 -0.14979  -6.7372e-05 | 77 -0.02852   4.6740e-05 | 78 -0.01291  -6.5362e-05
6 637 -log(L): 1536.79  Spbio: 64292.6 93089.1
so there are 78 estimated parameters

Then with 3.30 on the files converted by ss_trans I get:
 82 -0.14977  -1.2559e-06 | 83 -0.02850   8.5391e-07 | 84 -0.01289  -1.2101e-06
7 732 -log(L): 1535.18  Spbio: 64330.8 93058.1
note there are now 84 estimated parameters because 3.30 is turning on late recrdevs and and one forecast devs.  This can be turnedoff
my comparison of vuln_bio also is similar between 3.24 and 3.30

**Comment by Cole-Monnahan-NOAA** [comment]
@Rick-Methot-NOAA thanks for digging into that. I tried my best to get sstrans to work but wasn't able to track that one down so abandoned it. This is super helpful.

Can you clarify what's going on between

ss -nohess -maxI 0
and
ss -nohess -maxI -1
and
ss -nohess -phase 500 -maxfn 0

I'm surprised those are different. Also -maxI isn't in the ADMB documentation nor in the SS manual.  It looks like it's read in [here](https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/dddd7bb3ac42c5d7484a2a3667a769cbca044d58/SS_readstarter.tpl#L207) using the command line. I always thought maxI = maximum iterations but this is referencing max phase?

I'd be happy to help contribute to the manual to better explain these options if you'd like.

**Comment by iantaylor-NOAA** [comment]
@Cole-Monnahan-NOAA, good question. I don't know what `-maxI` is doing and we could definitely do a better job of documenting the command-line arguments commonly used with SS. For starters, here's some related info that we could move into a future user manual.

Last October @k-doering-NOAA did some investigations comparing three options:

1. `ss -maxfn 0 -phase 50 -nohess` which uses generic ADMB commands,
2. `ss -nohess` after changing the starter file to have a maximum phase of 0, and 
3. `ss -stopph 0 -nohess` where `-stopph` (_stop phase_) is a Stock-Synthesis-specific command that is designed to be equivalent to option 2 above that was added in SS version 3.30.16 so that folks didn't have to edit the input files.

At that time they all worked the same but there were subtle differences in likelihood due to the addition of a dummy parameter required for options 2 and 3. @Rick-Methot-NOAA corrected that for 3.30.17, so now they should truly be identical.

What IS noted in the [SS 3.30.17 User Manual](https://vlab.noaa.gov/documents/259399/4513132/SS3.30.17_User_Manual.pdf/) (under "Generate .ss_new files" on page 160) is that `ss -stopph -1` will generate the .ss_new files without running the model or going through the dynamics at all. This can be useful for ss_trans.exe but also cases where you've added or changed some parameters and the model reads the input files but then crashes without getting to the point of writing the .ss.new files. Running with `ss -stopph -1` will let you see parameter labels in control.ss_new which might help identify something out of order.

**Comment by kellijohnson-NOAA** [comment]
maxI is legacy code that led to confusion because it was hard to determine if the trailing letter was an "eye" or "ell" because of the ambiguity in font rendering. Thus, @Rick-Methot-NOAA added a new feature that is documented in the manual called stopph, which is documented in [ss_model_tips](https://github.com/nmfs-stock-synthesis/ss-documentation/blob/ca342aaca2b0f77ba37f7324ffefd93970b6b8cc/User_Guides/ss_model_tips/ss_model_tips.Rmd#L49), in the manual [Section 'Running without estimation'](https://github.com/nmfs-stock-synthesis/ss-documentation/blob/7619b3ed31af3d8e12392875cc53acc71c125d98/12runningSS.tex#L137), and in [Getting_Started_SS](https://github.com/nmfs-stock-synthesis/ss-documentation/blob/ca342aaca2b0f77ba37f7324ffefd93970b6b8cc/User_Guides/getting_started/Getting_Started_SS.Rmd#L191).

**Comment by Cole-Monnahan-NOAA** [comment]
Thanks for that clarifications. I naively did a search for "-maxi" in the manual and so missed that. I think at least we could put in something like "...stopph (formerly maxI)..." and maybe note this feature in the ss_trans section?

Anyway, happy to help with dox where I can.

Thanks for the help. Closing this down as successful.

**Comment by Rick-Methot-NOAA** [comment]
Let me add that the -1 option for phase is a trap to allow SS to bypass the
procedure section and go straight to writing out the *.ss_new files.  Ian
covered the rest well.

Rick

**Comment by Cole-Monnahan-NOAA** [comment]
Ugg I hate to do this, especially on a Friday afternoon. But I'm actually in exactly the same place I was at the original post. It is true that Rick's solution got ss_trans working, but the models still do not match. 

So if I start the new 3.30.17 model from the old MLE values (carefully editing the new .par file), then the dynamics match and SSB and total biomass matches. But vulnerable does not. See this table of the first 4 years:

| Bio_all_old | Bio_all_new | SSB_old | SSB_new | Vuln_bio_old | Vuln_bio_new |
|---|---|---|---|---|---|
| 198302 | 198298 | 52752 | 52751 | 194111 | 175363 |
| 217842 | 217837 | 70210 | 70209 | 212047 | 191789 |
| 221928 | 221924 | 78661 | 78660 | 217585 | 196154 |
| 219026 | 219022 | 78632 | 78631 | 211659 | 190104 |

So same problem as posted above. Q, selex, everything matches on the parameter side. Now if I optimize, then I get this:

| Bio_all_old | Bio_all_new | SSB_old | SSB_new | Vuln_bio_old | Vuln_bio_new |
|---|---|---|---|---|---|
| 198302 | 220005 | 52752 | 58647 | 194111 | 194626 |
| 217842 | 241464 | 70210 | 77898 | 212047 | 212643 |
| 221928 | 245834 | 78661 | 87221 | 217585 | 217411 |
| 219026 | 242773 | 78632 | 87307 | 211659 | 210923 |

Now total biomass and SSB don't match, but vulnerable does! The opposite as above. I'm at a bit of a loss here. To get expected index (biomass vulnerable to survey) you pass numbers at age through selectivity, then convert to lengths and then weights, then apply Q right. I've checked all these things. I tried different months in the index column and it has a relatively minor impact. Is there some other timing setting that could be causing this to go awry? 

It really "feels" like Q is too small. When I optimize lnR0 gets larger to increa. Further, the annual ratio of vulnerable biomasses between the two models  (in the first case above) is: 
1.107, 1.106, 1.109, 1.113, 1.114, 1.108, 1.111, 1.112, 1.112, 1.114, 1.115, 1.113, 1.113, 1.110, 1.112
so not exactly constant but pretty close. Both cases have simple Q fixed at 1 (Q_parm[1]=0).

If anyone has thoughts on where to look I'd be happy to investigate them.

**Comment by Rick-Methot-NOAA** [comment]
please send Rick that edited par file

**Comment by Cole-Monnahan-NOAA** [comment]
After much back and forth we did figure out that there are some key differences here.

My 3.24U model had the timing as -1 0 and Rick shows above that this breaks ss_trans so he changed it to -1 0.5. That works and with a few minor tweaks 3.30 will run.

The expected index difference remains, however. It seems the closest I can get is to use month=1 for the index data, and month=7 for the comps, per Rick's suggestion. This improves things but it is still ~8% lower. So when I optimize the new 3.30 model it has a higher biomass (it estimates a larger R0) to compensate.

Bottom line is that 3.30 cannot replicate the survey timing option I had used in 3.24 due to how the ALK is calculated. Here is what Rick said about it: 

> I believe, without explicitly re-verifying, that 3.24 created the survey ALK using mid-year length-at-age.  This then creates  bodywt-at-age used for the survey as well as the expected survey length comp.  But possible that 3.24 had a special condition such that survey_timing = 0 would cause it to switch to using beginning of year ALK for these purposes.  Survey_timing is definitely always used as the elapsed time between beginning of year and the survey so survival to the time of the survey is N*exp(-survey_timing*Z).

> 3.30 creates the survey ALK using the subseason that is nearest in timing to the month of the survey.  So, with only 2 subseasons, this can be either the beginning of year or middle of year.

Note that if you use a timing of 0.5 in the 3.24 model it will match the 3.30 model. The specific issue here is that I had timing=0.

Hopefully that clarifies the issue to future readers, and that there really is no solution in this case besides get as close as possible and live with the differences.
