### ISSUE TITLE
Option to exclude bycatch fleets from the annual_F

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#200]
This suggestion came up during a discussion with SEFSC. Some models include red tide as a fleet, but in some cases, it could be helpful to not include them in the benchmarks.

(@Rick-Methot-NOAA , please feel free to edit the comment/title of this issue if I did not capture it well!)

**Comment by Rick-Methot-NOAA** [comment]
random notes on what this will take:
What this will take:

- YPR_mask(f) is created in readdata using:
-           if(bycatch_setup(f,2)==2)  //  omit bycatch fleet catch from YPR optimize
-           { YPR_mask(f)=0;   }
-- So need to use this to exclude from annual_F and annual_catch also, or create new option by creating bycatch_setup(f,2)==3 to extend the exclusion and maintain backward compatibility.
- note that it cannot work if using Z-M method to get F, that is without a lot of added code to exclude bycatch fleets from that Z.
- easy to add exclusion of bycatch fleet if doing sum of Hrate
- use exclusion when accumulating annual_catch(y) so that exploitation rate also will be as desired
- in equil_calcs, looks like YPR_mask(f) is the tool to use.
-in equil_calc,  apply exclusion when calculation equ_F_std.  YPR_opt is already using YPR_mask (which was the target usage).  But equ_F_std was still using YPR_dead to report exploitation rate.  So bycatch could be excluded from the search for a target F, but the reported F was including bycatch.
- in forecast code, F_std is calculated directly rather than using annual_F(y,1) as intermediary.  
-

**Comment by Rick-Methot-NOAA** [comment]
in forecast, this code is within the season loop, so the initialize to 0.0 seems wrong:
            if((Fcast_Loop1==2 || Fcast_Loop_Control(1)==1) && ABC_Loop==1)  // get variance in OFL
            {
            	Mgmt_quant(Fcast_catch_start+N_Fcast_Yrs+y-endyr)=0.;
              for (f=1;f<=Nfleet;f++)
              {
                if(fleet_type(f)==1)
                {Mgmt_quant(Fcast_catch_start+N_Fcast_Yrs+y-endyr)+=catch_fleet(t,f,2);}
                else if (fleet_type(f)==3)
                {}  //  survey
                else if(bycatch_setup(f,2)==1) //  bycatch
                {Mgmt_quant(Fcast_catch_start+N_Fcast_Yrs+y-endyr)+=catch_fleet(t,f,2);}
              }
            }

**Comment by Rick-Methot-NOAA** [comment]
The solution outlined above was investigated and a branch created.  However, the code changes necessary in FORECAST were complex and would need much testing.  Nevertheless, this branch may have some useful code changes to compare and consider.

The alternative approach that was taken and completed was to implement git issue #45 such that red tide effect on natural mortality can be done as a predator, which inherently removes it from any F output issues.

Closing this issue.
