### ISSUE TITLE
bin-specific comp logL wrong in compreport for D-M; make comp logL code modular with function

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#219]
Thanks Grant Thompson for reporting the following:

> ...I was hoping that the log likelihoods listed in CompReport.sso for a given year/fleet/kind would sum to the value listed in the FIT_LEN_COMPS or FIT_AGE_COMPS section of Report.sso, but they are not even close.
> 
> I am using the Dirichlet-multinomial option, and I note that the SS change log includes an entry for 4/5/21 referencing "change logL for D-M composition," so I was wondering if perhaps the change did not get carried over into the code that generates the CompReport.sso file (just a wild guess on my part). ...

Investigate this and see if that is what is going on. (KD: we don't test CompReport.sso at all in our testing routines, so this is certainly possible)

**Comment by Rick-Methot-NOAA** [comment]
I think we need a code review here.

In ss_prelim, there is:
      int z1=tails_a(f,i,1);
      int z2=tails_a(f,i,2);
      offset_a(f,i) += gammln(nsamp_a(f,i) + 1.) -
        sum(gammln(1. + nsamp_a(f,i)*obs_a(f,i)(z1,z2)));

then in ss_objfun, there is:
          age_like(f,i) = -offset_a(f,i);  //  so a perfect fit will approach 0.0
and
              if(Comp_Err_A(f)==1) dirichlet_Parm=mfexp(selparm(Comp_Err_Parm_Start+Comp_Err_A2(f)))*nsamp_a(f,i);
              if(Comp_Err_A(f)==2) dirichlet_Parm=mfexp(selparm(Comp_Err_Parm_Start+Comp_Err_A2(f)));
and
                temp+=sum(gammln(nsamp_a(f,i)*  obs_a(f,i)(tails_w(1),tails_w(2))
                               + dirichlet_Parm*exp_a(f,i)(tails_w(1),tails_w(2))));
                temp-=sum(gammln(dirichlet_Parm*exp_a(f,i)(tails_w(1),tails_w(2))));
and
              age_like(f,i)-=temp;

then in write_report, the age_like are output for each obs in fit_age table, and these sum to the total reported logL
          age_like(f,i) = -offset_a(f,i);  //  so a perfect fit will approach 0.0

**Comment by iantaylor-NOAA** [comment]
I'm worried that I made an error in the changes to the DM likelihood associated with change in the code to add the constant of integration as discussed under https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/31.
Grant confirmed by email back in August that a model run in versions before and after that change had the same parameter estimates, so the issue seems to just be with the added constant.

**Comment by Rick-Methot-NOAA** [comment]
I created a test case from "simple" in which I verified that for multinomial with both length and age comp:
a) logL reported in fit_age and fit_length matches the sum of the bin specific logL in compreport.sso
b) by creating an input observation from the expected values output, verify that the model fits this perfectly and that it's logL is near 0.0, as it should be because it includes subtraction of an offset which is the logL for a perfect fit.  

Then switched to test case from hake_2018 that has only age comp and uses D-M.
It passes neither of the comparisons that are passed for multinomial.
Problem 1:  calculation of offset seems not to be using the dirichlet parameter
Problem 2:  reporting of bin-specific logL is not using D-M calcs.  But Pearson residuals do appear to be using D-M calcs
Problem 3:  logL of D-M has a component that is not bin-specific.  If we want the compreport logL output to sum to match the overall logL of that observation, then this component will need to be spread across the bins of that observation.

**Comment by iantaylor-NOAA** [comment]
Sorry for all these issues. I just looked through the changes in https://github.com/nmfs-stock-synthesis/stock-synthesis/pull/132/files. I thought that the whole point of the offset was that it represents the part of the likelihood which is independent of the parameters, and thus can be calculated in SS_prelim.tpl.

I tried to find notes related to checking the likelihood against the Thorson et al. paper but unfortunately haven't found them yet. Also, I'm on leave the next two weeks but can prioritize working on this for the week of Jan 3.

**Comment by Rick-Methot-NOAA** [comment]
The offset for D-M that is in place now may well be as good as it can be.  Don't sweat it.

**Comment by iantaylor-NOAA** [comment]
@Rick-Methot-NOAA, I finally took the time to double-check the implementation of the Dirichlet-multinomial likelihood and reread your note above https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/219#issuecomment-997059352 from December.

I verified outside of SS3 that the DM likelihood (when choosing the linear parameterization) matches equation (10) from Thorson et al. (2017) shown below.
![image](https://user-images.githubusercontent.com/4992918/153302773-d38e003e-333a-44f5-a830-ffd45469cab2.png)

When revising the DM offset in Feb 2021 (#31), I failed to understand the role of the offset for multinomial likelihood as you noted in the comment referenced above. That is, for the multinomial, I now see that the goal of the offset is to make the logL approach 0.0 for a perfect fit, not to match the full likelihood equation including normalizing constant. So given the important log-likelihood term of `n*obs*log(exp)`, the offset is set to `-n*obs*log(obs)`. 

Having the logL approach 0 for perfect fit probably has lots of benefits, including keeping the scale of all the likelihood contributions on a similar order of magnitude (in contrast to the current DM likelihood which can have really large values, and can be negative as well). However, this approach gets in the way of the one perceived benefit of having the DM likelihood include the constant term, which is facilitating comparing the DM vs multinomial likelihoods, as noted in https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/31#issue-737136387.

Now that I understand the difference between the two implementations I have a few questions on possible few ways forward.
1. Would there be any purpose in giving the user the option of the multinomial likelihood with the full constant term to facilitate comparison of the two likelihood options? I presume this comparison would only work if the input sample sizes were not adjusted, so maybe this wouldn't be valuable after all since we typically always weight the comp sample sizes when using the multinomial likelihood.
2. Is there a better offset for the DM likelihood that would bring the scale of the values down, or should we just stop messing with it and leave it as is, matching the published equations?

@james-thorson-NOAA, do you have any thoughts on this?

**Comment by iantaylor-NOAA** [comment]
Looking back over https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/219#issuecomment-997059352 above yet again, I see that the DM likelihood values should change in future models no matter what we decide on the two questions I just posed in order to resolve the problems related to bin-specific logL so that the reported values are correct and the compreport's logL output sums to match the overall logL of that observation.

**Comment by James-Thorson-NOAA** [comment]
My recommendation is that we want to allow the loglikehood to also be comparable between the DM and multinomial as primary goal (thus including the integration constant for both), but allowing a switch to compute the loglikelihood measured relative to a saturated fit.  This is one step along the path towards computing percent-deviance-explained ... a standard diagnostic for GLMs, which involves calculating the saturated value (which I assume is what is meant by a renormalization that results in a 0 value for a "perfect fit") but also one or more "null values" that could be computed by stripped out recruitment deviations or something.  So I see the value of the renormalization of log-likelihoods to have 0 correspond to perfect fit, but think that's a secondary concern that should be accessed through an explicit flag. 

just my two cents :)

**Comment by Rick-Methot-NOAA** [comment]
Reporting bin-specific contribution to the logL for each bin was the challenge I saw because the offset depends on the D-M adjusted sample size, so cannot be pre-computed.
So, whatever we do, I think we should start by creating multinomial and D-M functions that can be called, rather than the current spaghetti code that repeats these complex equations for length and age and males and females, and the for generalized size freq.
Then we could create offset on the fly as needed by calling fxn once to get the offset using (n, obs_comp, obs_comp, tails) and then again with  (n, obs_comp, exp_comp, tails).

**Comment by James-Thorson-NOAA** [comment]
My TMB code is below ... I recommend writing it out more spaciously like this (and assume a compiler can manually compress the multiple additions with no loss of efficiency) and putting it in some distributions.cpp file or whatever, please tell me if you want help.

```cpp
template<class Type>
Type ddirmult( vector<Type> x, vector<Type> prob, Type ln_theta, int give_log=0 ){

  // Pre-processing
  int n_c = x.size();
  vector<Type> p_exp(n_c);
  vector<Type> p_obs(n_c);
  Type Ntotal = x.sum();
  p_exp = prob / prob.sum();
  p_obs = x / Ntotal;
  Type dirichlet_Parm = exp(ln_theta) * Ntotal;

  // https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/main/SS_objfunc.tpl#L306-L314
  // https://github.com/James-Thorson/CCSRA/blob/master/inst/executables/CCSRA_v8.cpp#L237-L242
  // https://www.sciencedirect.com/science/article/pii/S0165783620303696

  // 1st term -- integration constant that could be dropped
  Type logres = lgamma( Ntotal+1 );
  for( int c=0; c<n_c; c++ ){
    logres -= lgamma( Ntotal*p_obs(c) + 1.0 );
  }

  // 2nd term in formula
  logres += lgamma( dirichlet_Parm ) - lgamma( Ntotal+dirichlet_Parm );

  // Summation in 3rd term
  for( int c=0; c<n_c; c++ ){
    logres += lgamma( Ntotal*p_obs(c) + dirichlet_Parm*p_exp(c) );
    logres -= lgamma( dirichlet_Parm * p_exp(c) );
  }

  if(give_log) return logres; else return exp(logres);
}

```

**Comment by Rick-Methot-NOAA** [comment]
Thanks Jim.  This code is exactly what I planned to write out in ADMB.  Will put it into the SS file SS_miscfxn.tpl
