### ISSUE TITLE
allow more reporting of standard deviation

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#239]
Request from Max C.: 

> However, I wonder if there is a way to, in future SS release, to augment the options for “read specs for more stddev reporting” at the end of the control file.
> 
> At the moment, it works as that if you want to get extra sd.dev of some of the estimates (I am particularly interested in st.dev of the number at age/length in the population), the extra control allow you to choose only one year at the time (if I get it right). I think it would be really useful for simulations purposes as MSE, to be able to get the st.dev of, for example, the number at age/length in the population for the entire time series at once.
> 
> Just a suggestion for future SS iterations

**Comment by Rick-Methot-NOAA** [comment]
possible, but the time to calculate all those variances would get huge.  I do not see how they would be useful in MSE context.

**Comment by SteveTeo-NOAA** [comment]
Hi Rick & Kathyrn,

Somewhat related request.

For the NP albacore assessment in March, we got new reference points with the depletion denominator as the dynamic SSB0. Right now, I am using the extra SD feature to get the uncertainty for the dynamic SSB0 and the correlations in the cor file to get the covariance between SSB and dynamic SSB0, and calculating the uncertainty for depletion after the fact. Would be nice to get that as an option (probably as an option in the starter file for depletion reporting).

Also, the Japanese scientists are asking me to get the uncertainties for the F-at-age so that they can run their projections with the correct uncertainties. Right now, the hacky way to do it is to set the average F reporting in the starter file to a specific age and running it 15 times (once for each age). If it is possible to set that as an option in the starter file or the extra SD reporting in the control file, that would be great. Thanks.

**Comment by Rick-Methot-NOAA** [comment]
Hi Steve,
What's your timeline on needing these?  We'll want to work with you to have a relevant example and for you to help with the testing.
I assume that the F report would be the total F across all fleets.  It might be too wonky to even allow that in a multi-area situation because F can only be done per area.  Perhaps the report could also be by area.

**Comment by SteveTeo-NOAA** [comment]
Rick,

The assessment meeting is March 20-27. So ideally, by March. But even if
that is too tight, it would still be useful over the long run.

I can definitely help with the testing. We can use the 2020 model for
testing. The 2023 model would be similar in structure. I can send you the
2020 dat and ctrl files outside of github, if you would like that.

Yes, the F would be total F across all fleets.  The model is a single area
model (fleet-as-areas), so by area would be fine.

Thanks for your help.

Teo

**Comment by Rick-Methot-NOAA** [comment]
I can calculate total F-at-age from Z-at-age minus M-at-age
That F-at-age will be by:
season (within year)
area
sex * morph * platoon.

So what set of options should we provide the user?  The current set of options for other extra_std outputs has evolved "diversely".

for selex:
user picks length vs age
user picks which bins (ages) to output
user picks 1 year and 1 fleet
output is for season 1 and growth_morph 1 if relevant
area not relevant

for growth:
season 1 of endyear hardwired
user selects growth morph
both sexes are output

for N-at-age:
user selects one area, or selects to sum all areas
user selects year
season 1 is hardwired
males added to females

for M, the output is for the middle platoon, for a selected sex and morph, for season 1 of endyr, and for area 1.
first season of endyr is hardwired
user selects one growth_morph
user selects a subset of ages
both sexes are output


So......  What to do?

**Comment by SteveTeo-NOAA** [comment]
Hi Rick,

For my purposes, it would be:

user selects one area, or selects to sum all areas
user selects year
user selects one season or selects to sum all seasons (if need to fix, I
would sum to all seasons)
user selects 1 sex, morph, platoon or selects all
user selects age range (output will be by age)

**Comment by Rick-Methot-NOAA** [comment]
Thanks for the feedback.
The challenge I see is that the concept of a population wide F does not mesh with a multi-area situation.  What's the algorithm to get population F if one area has few fish and high F, while other areas have high N and low F?  Even if I got overall Z-at-age by summing N-at-age across areas and calculating Z=ln(N(t)/N(t-1)), it still is highly influenced by the relative numbers per area.  I think for now I will stick with user selects one area.

**Comment by SteveTeo-NOAA** [comment]
Good point Rick. Selecting one area works for me.

**Comment by Rick-Methot-NOAA** [comment]
@SteveTeo-NOAA 
Hi Steve.  I dropped the ball on this.  What is status of need on your end?

**Comment by SteveTeo-NOAA** [comment]
Hi Rick,

I am set. Thanks.

**Comment by Rick-Methot-NOAA** [comment]
OK.  Closing issue
