### ISSUE TITLE
Length data bin widths

### ISSUE THREAD

**Issue by shanae-allen** [nmfs-stock-synthesis/stock-synthesis#306]
Hello SS community! In SS can you specify different bin widths for different data sources? For instance, one of our length data inputs is from a visual survey. The measurement error for this survey is greater than our other surveys, so that a 5 cm bin width is more appropriate compared to, say, a 2 cm bin width for our dockside sampling surveys. Our conditional age at length data is also at a finer scale (1 or 2 cm bin width). Thank you! Shanae (FL FWC)

**Comment by k-doering-NOAA** [comment]
Hi @shanae-allen , thanks for asking this. [Generalized size comps](https://nmfs-stock-synthesis.github.io/doc/SS330_User_Manual.html#generalized-size-composition-data) can be used to input different bin sizes. I think for conditional age at length data, though, that needs to be put in in the regular length and age comps. 

Hope this helps - and hopefully others will chime in if they also have advice!

**Comment by shanae-allen** [comment]
Thank you for the very quick response! We will try that.

**Comment by k-doering-NOAA** [comment]
Best of luck! Feel free to reopen this if needed.

**Comment by Rick-Methot-NOAA** [comment]
each CAAL observation specifies a min and max **population** bin, which can be finer than data length bins.  So, you may be able to do CAAL with different length ranges for different observations/sources.

**Comment by shanae-allen** [comment]
Thank you Rick! I mistakenly thought that CAAL data were in terms of data
bins, rather than population bins, so thank you for clearing that up!

**Comment by iantaylor-NOAA** [comment]
Hi @shanae-allen, your confusion is reasonable because you really have 3 choices for the Lbin_lo and Lbin_hi values used for conditioning the CAAL data:

> Bin method for age data
>    1 = value refers to population bin index
>    2 = value refers to data bin index
>    3 = value is actual length (which must correspond to population length bin boundary)

(from User Manual section 7.16.3 Age Composition Specification: https://nmfs-stock-synthesis.github.io/doc/SS330_User_Manual.html#age-composition-specification)

My preference is to always use the actual length because it creates the least confusion. In your case if you want to condition on 1cm bins, you would specify 1cm population length bins and then provide the same value for low and high in the CAAL data. That is, Lbin_lo = 30, Lbin_hi = 30 would include ages from all fish between 30.0cm and 30.999cm, whereas Lbin_lo = 30, Lbin_hi = 31 would condition on the 2cm range going up to 31.999.

@Rick-Methot-NOAA, instead of having folks increase the bin width to account for measurement uncertainty (as in this case where the visual survey is imprecise), does it make sense as a concept to have the equivalent of ageing error applied to length data? It's conceivable that you could experimentally measure the precision of the visual length measurements to guide the choice of the error estimation in a more satisfying way than just wider bins. It's hard to imagine that this would rise to the top of the to-do list anytime soon, but perhaps worth thinking about for future models.

**Comment by Rick-Methot-NOAA** [comment]
Yes, something like that would be an improvement.
Reminds me of a feature from the pre-ADMB FORTRAN version of synthesis that was not carried forward.  That feature was mis-sexing.  I added it because the rare very large male sablefish was probably just a miscoded female; easy to do with paper forms on a rolling deck.

**Comment by shanae-allen** [comment]
Ah yes, I always use bin method #3 for age data (actual length), but I
mistakenly thought those lengths had to correspond to the data lengths
rather than the population lengths. Luckily I never had a problem with this
incorrect assumption before because my data lengths matched my population
lengths. In the future though I would like to experiment with finer scale
population bins.
I agree that applying something similar to an ageing error matrix rather
than increasing bin widths is a much more refined way of dealing with
measurement error in length.
Thank you both for your valuable feedback!
