### ISSUE TITLE
inquiry on the selex type:42

### ISSUE THREAD

**Issue by yukio-takeuchi** [nmfs-stock-synthesis/stock-synthesis#363]
Hi, I am just looking source codes for selex type 42 ( an 27) (SS_Label_Info_22.7.27 and SS_Label_Info_22.3.27) in SS_selex.tpl

Regardless of age or size selectivity, if selex type is 42, 1st parameter (sp(1) seems to have two roles i.e., "code" and "low_bin". On the other hand  sp(3) seems to be not used if selex type is 42. I am wondering if "low_bin" and "high_bin" should point to sp(2) and sp(3) respectively for selex type 42.

**Comment by iantaylor-NOAA** [comment]
Thanks @yukio-takeuchi, there's definitely a bug in there which I think is my fault due to the changes introduced in this pull request: https://github.com/nmfs-stock-synthesis/stock-synthesis/pull/241 from January where I erroneously assumed that the first parameter is always the code, when in fact it appears that for selectivity pattern 42, the two extra bin range parameters precede the remaining parameters as indicated by the parameter labeling here: https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/main/SS_readcontrol_330.tpl#L3398-L3404.

I've attempted a fix in commit 54b2993.
@yukio-takeuchi and @Rick-Methot-NOAA, can you look this over to see if the change makes sense or if we should make further modifications before opening a pull request?

I can also improve the documentation for selex pattern 42 to clarify the parameter order.

**Comment by yukio-takeuchi** [comment]
Thanks @iantaylor-NOAA for your quick work. It seems, the change is relevant to make type 42 workable. 

Thanks again.

**Comment by iantaylor-NOAA** [comment]
Thanks @yukio-takeuchi for taking a look.
@Rick-Methot-NOAA, I just opened PR #364 so you can just review this once if it looks OK.
