### ISSUE TITLE
`niter` is only available via `write_SS_summary()` and not `write_big_report()`

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-stock-synthesis/stock-synthesis#365]
https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/0adb061cf7d7fb635ea34b346ed53b9894c5f7ad/SS_write.tpl#L388

Any objection to adding the number of iterations to Report.sso?

**Comment by Rick-Methot-NOAA** [comment]
fine by me.  Shall I add it to the Tweedie & D-M branch now under review?

**Comment by kellijohnson-NOAA** [comment]
That would be great @Rick-Methot-NOAA . Thank you.

**Comment by iantaylor-NOAA** [comment]
This issue helped me realize that I was accidentally returning the new values as characters and not numeric. That's been fixed in r4ss commit https://github.com/r4ss/r4ss/commit/9590ba1d2729b4aac52911c7f66026b12d79cd92. The new output is returned by SS_output() as `$N_iterations` and `$Final_phase`.
