### ISSUE TITLE
[Bug]: ForeCatch not quite equal to OFLCatch * buffer

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-stock-synthesis/stock-synthesis#485]
### Describe the bug

The attached petrale sole model [2023.a034.011_forecast_SR.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/12177669/2023.a034.011_forecast_SR.zip) (input and output) has a forecast buffer that is set to 0.935 in 2025. 

The OFLCatch_2025 is 2517.67 and the ForeCatch_2025 is 2356.47, but applying the 0.935 buffer to the OFL is different by about 2 tons: 2354.021. In that year the biomass is slightly above the 0.25 control rule inflection for flatfish so no ramping down in forecast catch should be occurring (unlike subsequent years). I see that the value of ABC_buffer in TIME_SERIES is 1.00119 for 2025, so maybe that's the source of the difference, but I'm not sure how that value is calculated or if I have something set wrong in the forecast file.

The differences are small, but large enough to be noticed by the review panel. And one other model that I looked at had an exact match (within the 0.01 precision reported).

@Rick-Methot-NOAA, do you think this is just some form of rounding error or the result of an iterative process that doesn't provide an exact match, or is there something else going on? 

And if there's not a quick solution, do you have guidance on what would be the most accurate source of ACL values for management: the ForeCatch from the model or the OFLCatch multiplied by the buffer outside the model?

### To Reproduce

Look at attached files.

### Expected behavior

more precise equality for ForeCatch_2025 = OFLCatch_2025 * 0.935

**Comment by Rick-Methot-NOAA** [comment]
The logistic joiner for the control rule is almost certainly the source of this small discrepancy.
https://vscode.dev/github/nmfs-stock-synthesis/stock-synthesis/blob/main/SS_benchfore.tpl#L2624-L2648

If you need exact, applying buffer to OFL seems logical alternative

**Comment by chantelwetzel-noaa** [comment]
I have looked into this issue as well. I am not convinced that there is an issue in the joiner for the harvest control rule since this issue is not occurring for two different models (canary and copper). The canary model is using the same executable as Ian's model (#V3.30.21.00;_fast(opt);_compile_date:_Feb 10 2023) and the copper model is also using the same version but the safe executable. However, looking over the model files that Ian has shared I have been unable to find a setting that would be causing the buffer value to not be applied correctly.

**Comment by Rick-Methot-NOAA** [comment]
The wobble caused by the joiner will only occur very close to the joiner, so will be case-specific.  Perhaps this joiner needs to be made steeper.  I just examined all the joiners.  This one is the shallowest (10).  Others use 20, 30, 40, 50, 100, even 1000!.  This should be cleaned up after an evaluation of a good default and then made into a function.

**Comment by Rick-Methot-NOAA** [comment]
Turns out that there already is Join_Fxn in the file with misc_fxn.  It uses a steep value (1000), but is only called from the recruitment code.   All other uses of join concept have custom code.  So, another one of my half-implemented ideas.
