### ISSUE TITLE
add dynamic Bzero as option for denominator in depletion calculations

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#69]
Imported from redmine, Issue [#75357](https://vlab.ncep.noaa.gov/redmine/issues/75357)
 Opened by @RickMethot on 2020-02-25
Status when imported: New
 
Depletion is the ratio of current SSB to a reference SSB.  There are two hardwired reference SSB values:  SSB_virgin calculated at beginning of time series, and SSB_unfished which uses the benchmark definitions (including benchmark range of years for biology).  Also, SSB_unf can be calculated each year of the time series in order to do spawner-recruitment using time-varying baseline.

The best denominator to use gets complicated when there is time-varying biology.

The proposal is to provide user control of these options.  First step would be to scope out the range of needed options.

**Comment by Rick-Methot-NOAA** [comment]
Several options are now available per:
1 # Depletion basis:  denom is: 0=skip; 1=rel X*SPBvirgin; 2=rel SPBmsy; 3=rel X*SPB_styr; 4=rel X*SPB_endyr; values; >=11 invoke N multiyr (up to 9!) with 10's digit; >100 invokes log(ratio)
0.35 # Fraction (X) for Depletion denominator (e.g. 0.4)

So, I see no need to add more options unless someone has a specific suggestion.

**Comment by Rick-Methot-NOAA** [comment]
For the NP albacore assessment in March, we got new reference points with the depletion denominator as the dynamic SSB0. Right now, I am using the extra SD feature to get the uncertainty for the dynamic SSB0 and the correlations in the cor file to get the covariance between SSB and dynamic SSB0, and calculating the uncertainty for depletion after the fact. Would be nice to get that as an option (probably as an option in the starter file for depletion reporting).

**Comment by jimianelli** [comment]
just a caution in computing sd-report for dynamic B0 calcs, and you probably already came across this that the initial ratio of SSB/SSB_no_fishing in year 1 will have a zero variance...so need to start off in a later year. 

An other comment (sorry if misses the basic point, but changing biology should have no impact):
1. In the sd_phase() run the model at point estimates for each year of recruitment (R_hat and R_SRR where R_hat are the actual N-at-age-zero I guess and R_SRR are from the model estimate from the SRR) and biology but with zero fishing mortality, compute the SSB_nf (spawning biomass w/o fishing)
2. If SRR, compute R_SRR_nf as a function of SSB_nf and point estimates of SRR params (time varying or not)
3. Adjust N-age0 as equal to R_hat*R_SRR_nf/R_SRR (this will account for differences in SSB under no fishing and the estimated SRR; e.g., if R_SRR_nf is > R_SRR it will inflate the N-age0 appropriately for the dynamic B0 calc)
4. re-run model time series but with N-age0 from step 3, maybe iterate a fixed number of times (2?) with updated SSB (but probably polishing peanuts at this stage, adjustment due to SRR typically not huge).

**Comment by Rick-Methot-NOAA** [comment]
Hi Jim.  I'm not seeing the merit in the adjustments in your step 3 and 4.  The current SS3 procedure to get dy_B0 runs the model with F = 0 and with R = R_SRR*recdev.  It does not use the Rhat from the fished iteration.  I understand that there may be interest in a dy_B0 approach that uses Rhat, but that is a bigger change than the current request to use dy_B0 as denominator for depletion.
Thanks for reminder regarding the first year variance.

**Comment by Rick-Methot-NOAA** [comment]
programming notes:
code already finds value for first_catch_yr and uses it to restrict range of years for depletion calculation.

dynamic Bzero for all years stored as:
      k = Do_Dyn_Bzero;
      for (j = styr - 2; j <= YrMax; j++)    {
        Extra_Std(k) = SSB_yr(j);     k++;

denominator for depletion calculation stored as:
// depletion must start in year AFTER first catch.  It could vary earlier if recdevs happened enough earlier to change spbio, but this is not included
        if ((depletion_basis > 0 && y > first_catch_yr) || y == endyr)
        {
          N_STD_Yr_Dep++;
          STD_Yr_Reverse_Dep(y) = N_STD_Yr_Dep;
        }
...... then numerator for depletion stored as:
    if (STD_Yr_Reverse_Dep(y) > 0)
    {
      depletion(STD_Yr_Reverse_Dep(y)) = SSB_yr(y);
    }

then need to add new case to following switch and process it yr by yr using dy_B0 in denominator:
  switch (depletion_basis)
  {
    case 0:
    {
      depletion /= SSB_virgin;
      break;
    }

**Comment by iantaylor-NOAA** [comment]
I think our workflow has been to leave it open with the "resolved" label until after the release that includes this change. 
See #122.

**Comment by SteveTeo-NOAA** [comment]
I just tried to use dynamic B0 as the denominator for the depletion calcs (option 5 in the starter file) for the albacore assessment but SS threw an error when calculating the derived quants.

Differentiating 8 derived quantities: array bound exceeded -- index too high in prevariable::operator()

Was fine when using option 1 (SPBvirgin)

**Comment by Rick-Methot-NOAA** [comment]
Hi Steve,
Please send the input files that cause the error to nmfs.stock.synthesis@noaa.gov.

**Comment by Rick-Methot-NOAA** [comment]
see the latest pull request for the new warning message to avoid this error
