### ISSUE TITLE
implement transitional SPR calculations

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#88]
Imported from redmine, Issue [#83053](https://vlab.ncep.noaa.gov/redmine/issues/83053)
 Opened by @RickMethot on 2020-09-21
Status when imported: New
 
Some users are interested in transitional SPR calculations per Mace (1996).  

This will be easier if natM is stored by "t" over the whole time series rather than by "s", or better as both.

**Comment by Rick-Methot-NOAA** [comment]
- [ ] store natM by t and area (p), so same as Z_rate(t,p,g)
- [ ] do not add pred_M2 to natM; keep separate and add in pred_M2 only when calculating Zrate
- [ ] pred_M2 is effectively a fleet, so is area-specific as are all fleets
- [ ] transitional SPR calc needs access to Z_rate, natM, N, fec by t,p,g
- [ ] add the transitional_SPR report to the Z report

**Comment by e-gugliotti-NOAA** [comment]
@Rick-Methot-NOAA is this issue fully closed or does there still need to be more work on it? It isn't marked "done" in the summary view and there are still 2 items above that look like they need to be checked off but it says it's closed.

**Comment by Rick-Methot-NOAA** [comment]
Thanks for noticing that this issue is in limbo.  The completed step now stores natural mortality (natmort) as an annual quantity and I believe the record should show that that was merged back into MAIN, then other issues took priority.  Could you edit the existing issue to more clearly show that it just did the annual storage of natmort.  Then create a new wishlist issue for transitional SPR.  Transitional SPR will be implemented as a new report.
