### ISSUE TITLE
allow separate Dirichlet-multinomial parameter for discard vs retained length comp

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#93]
Imported from redmine, Issue [#83862](https://vlab.ncep.noaa.gov/redmine/issues/83862)
 Opened by @iantaylor-NOAA on 2020-10-14
Status when imported: New
 
All the data-weighting options for composition data (Dirichlet-Multinomial parameters, sample size adjustments, and lambdas) apply equally to all partitions within a fleet. Many west coast groundfish stocks have much higher sample sizes of discards from the observer program than the shoreside sampling of retained fish. This likely leads to the discard data having a greater influence on model results than the retained fish which may not always be appropriate.

Providing a simple mechanism for separate weights by partition would be require some changes to the model input structure, such as
* a new Partition column next to ParmSelect in the table of comp likelihood specifications in the data file to allow separate D-M parameters by partition
* a new Partition column next to fleet in the "Input variance adjustments factors" in the control file for use in the McAllister-Ianelli or Francis methods
* a new Partition column (or repurposing the sizefreq_method column) in the lambda inputs (facilitating the use of different lambdas by partition seems like a lower priority)

Alternatively, some code could be used with existing input structure to implement this, such as adding 1000 to the fleet number in the variance adjustments factors to have it apply to partition 1 and 2000 to apply to partition 2 (although this applying an adjustment to data only from partition 0 would perhaps require the confusing use of adding 3000).
The table in the data file where the Dirichlet-Multinomial parameters are input always has a single row for each fleet, so this would require some other trick to create separate parameters for each partition within the existing input structure.

The assessment team at NWFSC has a strong interest in exploring this possibility, but we could also adjust the input sample sizes as a less elegant approach to testing the impact of separate data-weighting by partition.

**Comment by k-doering-NOAA** [comment]
Need to do this without changing the i/o for all users

**Comment by Rick-Methot-NOAA** [comment]
Thanks for the suggestions on the input options.

Good news is that the logL is already stored for each observation and each observation "knows" whether it is discard, retained, or combined.
So the only change is when the individual obs get combined into total logL:
      if(header_l(f,i,3)>0) length_like_tot(f)+=length_like(f,i);
so length_like_tot(f) needs to get a partition dimension.

similar dimension addition for length_lambda(f,phase)

then the total will need to use some matrix notation, not the elegant vector sumproduct summing as current:
   obj_fun += column(length_lambda,k_phase)*length_like_tot;

**Comment by k-doering-NOAA** [comment]
Just in case it got lost in the thread, this is needed for the next assessment cycle for west coast groundfish (work starts fall 2022)

**Comment by Rick-Methot-NOAA** [comment]
Yes.  This and DM for size comp are competing for next big change.

**Comment by Rick-Methot-NOAA** [comment]
@iantaylor-NOAA @kellijohnson-NOAA @chantelwetzel-noaa 
I'm looking to start this change, which will be very tricky regarding the internal indexing.
Question:  I am thinking of implementing this option for the D-M method first and perhaps only.  Would that be OK?

**Comment by iantaylor-NOAA** [comment]
Applying first to D-M makes lots of sense in terms of a pilot application to see how much difference we're seeing in the estimated weights. The question of only D-M being satisfactory in the long term could depend on how well we can get by with just D-M for those stocks where the weighting is estimated to be quite different.

In the most recent two cycles, the PFMC groundfish assessments have had a mix of D-M and Francis weighting, where the choice between them is typically driven by subject choices related to the plausibility of the results (e.g. for Big Skate the D-M seemed to work fine, but for Longnose Skate it put too much weight on the indices relative to the comps causing bad residual patterns and less realistic estimates of growth). However, it would be great if D-M worked for every stock because of the automated aspect and having separate weighting for discards and retained comps may cause it to perform better and allow us to move more fully in that direction.

I could see it being frustrating to not be able to compare D-M vs Francis with separate weights for discards and retained, but I supposed a hack to facilitate that comparison if someone thinks it's necessary would be to use the estimated D-M weights for discards vs retained to adjust the input sample size for the discards and then apply the Francis weighting with that fixed ratio embedded into the inputs. Also, if we're stuck with a single weighting option, that's one fewer challenge for the assessors to deal with. Comparisons of multiple methods are encouraged but not required by PFMC SSC: "STATs are encouraged to provide a rationale for the method they select and are encouraged to conduct sensitivity runs with the other methods." ([accepted practices guide link](https://www.pcouncil.org/documents/2021/02/accepted-practices-and-guidelines-for-groundfish-stock-assessments-february-2021.pdf/))

**Comment by kellijohnson-NOAA** [comment]
I think that just for D-M is fine Rick. I think that it will be a good proof of concept and force us to really figure out why there are differences between D-M and Francis rather than just defaulting back to what use to be used. I wonder if a little bit of research needs to be done on input sample sizes such that the composition data do not overwhelm the index data?

**Comment by Rick-Methot-NOAA** [comment]
Looked at the code and realize that the current indexing scheme that allows D-M parameters to be shared by multiple fleets is already complex.  Elaborating it to do partition also is going to be challenging.  May need a major overhaul of the I/O.
Currently, the code expects this input line for each fleet:
#_mintailcomp addtocomp combM+F CompressBins CompError ParmSelect minsamplesize

an alternative would be to read list of:
fleet, partition, mintailcomp addtocomp combM+F CompressBins CompError ParmSelect minsamplesize
-9999 to end reading

code could invoke this alternative approach by imbedding a flag in this current input:
3 # length bin method: 1=use databins; 2=generate from binwidth,min,max below; 3=read vector;   with values > 10 indicating to use alternative input

- [ ] change all vectors like:  Comp_Err_A(f)   to matrix:  Comp_Err_A(f,partition)
- [ ] create the alternative Input, including option to fill for all higher number fleets

**Comment by Rick-Methot-NOAA** [comment]
Thought about that, but it did not lend itself to obvious internal storage solution.  Will consider further before proceeding.

**Comment by iantaylor-NOAA** [comment]
That makes sense. I haven't thought about internal storage at all. We can adapt to whatever design is easiest to implement.

**Comment by Rick-Methot-NOAA** [comment]
not ready to do a pull request yet, but the I/O for new format is working:
2 # use length composition data (0/1/2) where 2 invokes new comp_comtrol format
.........
#_Using new list format for composition controls
#_fleet partition mintailcomp addtocomp combM+F CompressBins CompError ParmSelect minsamplesize
 0 0 0.0001 4e-07 0 0 0 0 1
 1 1 0.0001 2e-07 0 0 0 0 1
 1 2 0.0001 3e-07 0 0 0 0 1
 -9999 1 0.0001 1e-07 0 0 0 0 1
